## Some useful links and quotes

https://www.unesco.org/en/open-science

> Open Science has the potential of making the scientific process more transparent, inclusive and democratic.  It is increasingly recognized as a critical accelerator for the achievement of the United Nations Sustainable Development Goals and a true game changer in bridging the science, technology and innovation gaps and fulfilling the human right to science.

https://en.wikipedia.org/wiki/Open_science

> Open science is the movement to make scientific research (including publications, data, physical samples, and software) and its dissemination accessible to all levels of society, amateur or professional.

https://commons.wikimedia.org/wiki/File:To_deposit_or_not_to_deposit,_that_is_the_question_-_journal.pbio.1001779.g001.png

UNSW works: https://unsworks.unsw.edu.au

https://www.library.unsw.edu.au/research/publishing-and-sharing-your-research/open-access
https://subjectguides.library.unsw.edu.au/publishing/data


BOAI: https://www.budapestopenaccessinitiative.org/

Rainbow of open science practices

https://zenodo.org/record/1147025#.ZDyejLRBxhE

From https://blogs.uef.fi/ueflibrary-bors/different-ways-to-make-your-research-more-open/

> Remember:

>    Practicing open science is more than just sharing your publications.
    There are lots of opportunities to open up your work during the research lifecycle.
    Several funding bodies expect researchers to share, at least, publications and data.
    It does take a bit more work but there are many rewards.
    Everyone has a role. How can you contribute to making science and research more open (see figure below for inspiration)?
    
From https://unimelb.libguides.com/openresearch/data
See sections how to make your data open and how to make code and software open


## Some useful Presentation tips

To use the fontawesome pics in the presentation I had to upgrade quarto and install the extension in the project root directory:
```sh
quarto install extension quarto-ext/fontawesome
```

I had to modify the logo image to make the background transparent. I used [ImageMagick](https://stackoverflow.com/questions/12424018/how-to-replace-white-background-color-with-transparent-of-an-image-in-imagemagic):

```sh
cd img/
convert  ces-logo.png  -transparent white  ces-logo-transparent.png 
```